--- !ruby/object:RI::ClassDescription 
attributes: []

class_methods: 
- !ruby/object:RI::MethodSummary 
  name: datadir
- !ruby/object:RI::MethodSummary 
  name: inspect
comment: 
constants: []

full_name: Config
includes: []

instance_methods: []

name: Config
superclass: 
