--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:SM::Flow::P 
  body: Return the path to the data directory associated with the given library/package name. Normally this is just
- !ruby/struct:SM::Flow::VERB 
  body: "  &quot;#{Config::CONFIG['datadir']}/#{name}&quot;\n"
- !ruby/struct:SM::Flow::P 
  body: but may be modified by tools like RubyGems to handle versioned data directories.
full_name: Config::datadir
is_singleton: true
name: datadir
params: (package_name)
visibility: public
