### AUTOMATICALLY GENERATED.  DO NOT EDIT.
require 'merb-action-args'
require 'merb-assets'
require 'merb-haml'
require 'merb-builder'
require 'merb-mailer'
require 'merb-parts'
require 'merb-cache'
require 'merb-freezer'
require 'merb-slices'
require 'merb-jquery'
