require 'facets/kernel/__class__.rb'
require 'facets/kernel/__dir__.rb'
require 'facets/kernel/__get__.rb'
require 'facets/kernel/__set__.rb'
require 'facets/kernel/as.rb'
require 'facets/kernel/ask.rb'
require 'facets/kernel/attr_singleton.rb'
require 'facets/kernel/complete.rb'
require 'facets/kernel/constant.rb'
require 'facets/kernel/d.rb'
require 'facets/kernel/deep_copy.rb'
require 'facets/kernel/demo.rb'
require 'facets/kernel/ergo.rb'
require 'facets/kernel/here.rb'
require 'facets/kernel/in.rb'
require 'facets/kernel/instance.rb'
require 'facets/kernel/instance_assign.rb' # DEPRECATE
require 'facets/kernel/instance_class.rb'
require 'facets/kernel/instance_send.rb'
require 'facets/kernel/instance_variables.rb'
require 'facets/kernel/maybe.rb'
require 'facets/kernel/not_nil.rb'
require 'facets/kernel/object_class.rb'
require 'facets/kernel/object_hexid.rb'
require 'facets/kernel/object_send.rb'
require 'facets/kernel/p.rb'
require 'facets/kernel/populate.rb'
require 'facets/kernel/require_all.rb'
require 'facets/kernel/require_local.rb'
require 'facets/kernel/resc.rb'
require 'facets/kernel/respond.rb'
require 'facets/kernel/returning.rb'
require 'facets/kernel/silence.rb'
require 'facets/kernel/singleton_class.rb'
require 'facets/kernel/suppress.rb'
require 'facets/kernel/tap.rb'
require 'facets/kernel/try.rb'
require 'facets/kernel/val.rb'
require 'facets/kernel/with.rb'

# for 1.9
require 'facets/kernel/__callee__.rb'
require 'facets/kernel/__method__.rb'
require 'facets/kernel/instance_exec.rb'

